<a href="https://colab.research.google.com/github/abhishek18-blog/DataScience-and-ML/blob/main/Numpy_week2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
l1 = [1,2,3]
arr1 = np.array(l1)
# print(l1)
# print(arr1)

l2 = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(l2)

print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(np.arange(5,9,2))
np.arange(5,9)

[5 7]


array([5, 6, 7, 8])

In [ ]:
z1 = np.zeros((5,3))
print(z1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
z2 = np.eye(5)
print(z2)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
z3 = np.ones(5)
print(z3)

[1. 1. 1. 1. 1.]


In [ ]:
n1 = np.random.normal(170,10,250)
print(n1)

[170.95956066 169.26807015 171.48550899 166.71831556 170.73878233
 156.17031825 181.85840841 176.74483593 172.01207882 172.79554901
 159.0739978  161.49952565 162.38123177 166.53023274 167.79136084
 185.23742066 186.59121242 179.78062927 174.44941792 165.3411411
 170.02021607 176.96615167 166.94680791 169.25427196 182.32259814
 164.48311168 179.68642122 166.57313837 181.05222813 161.26188617
 179.86720978 155.11358058 186.9571053  182.44767985 181.77751526
 152.82902423 168.02387281 164.19052097 172.75020397 171.55441024
 167.83489071 170.74039292 187.5532672  153.42558956 176.28737386
 168.67161116 162.52066536 169.9409748  156.7559156  174.64198189
 177.40249743 168.21029666 183.11877572 166.09733384 173.58938719
 174.6382813  172.24260054 142.16758993 162.44368958 164.02620942
 171.81245355 163.02348273 156.44357856 156.11756855 151.64456398
 181.83571016 174.2173807  161.89691103 175.78831556 168.86727339
 171.7799678  166.55544819 163.16969745 169.53121082 190.63313332
 140.478483

In [ ]:
arr1 = np.random.randint(1,100,10)
print(arr1)

[77 54 63 91 26 69 93 92 20  7]


In [ ]:
arr2 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr2[2:6:2])
print(arr2.max())
print(arr2.min())
print(arr2.argmax())

[3 5]
10
1
9


In [ ]:
arr3 = np.array([1,2,3,4])
ar4=arr3.copy()
ar4[1:3]=5
slice = ar4[1:3]
print(slice)


ar4=arr3.copy()
ar4[1:3]=5
slice2 = ar4[1:3]
print(slice2)
slice2[0:7]=100
print(slice2)

[5 5]
[5 5]
[100 100]


In [ ]:
import numpy as np

# Create a NumPy array
my_array = np.array([10, 25, 5, 40, 15, 30])
print(f"The array is: {my_array}")

# Find and print the greatest number in the array
greatest_number = my_array.max()
print(f"The greatest number in the array is: {greatest_number}")

The array is: [10 25  5 40 15 30]
The greatest number in the array is: 40


In [ ]:
import numpy as np

# Create a base array
arr = np.array([1, 2, 3, 4, 5])

# Create a view of the array
view_arr = arr[2:4]

# Create a copy of the array
copy_arr = arr.copy()

# Check if they are views or copies
print("arr is a view or copy?", arr.base is None)  # arr is original, so it has no base
print("view_arr is a view?", view_arr.base is arr)  # Should print True, as view_arr shares data with arr
print("copy_arr is a copy?", copy_arr.base is arr)  # Should print False, as copy_arr has its own data
